'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace PizzaShop.Properties


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PizzaShop.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bbq_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bbq_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bbq_pizza_small As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bbq_pizza_small", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property breakfast_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakfast_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_left As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_left", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_left_selected As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_left_selected", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_right As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_right", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_right_selected As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_right_selected", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_whole As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_whole", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property button_whole_selected As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_whole_selected", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property cheese_mozz As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese_mozz", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property cheese_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property cheese_pizza_small As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese_pizza_small", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property close_white_thick_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_white_thick_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property close_white_thin_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_white_thin_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property crust_handtossed As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crust_handtossed", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property crust_pan As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crust_pan", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property crust_stuffed As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crust_stuffed", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property crust_thin As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crust_thin", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Custom_920x250 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Custom_920x250", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property custom_white_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("custom_white_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property error_red_18x18 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_red_18x18", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property info_white_thick_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_white_thick_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property info_white_thin_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_white_thin_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Italiano As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Italiano", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property loaded_potato_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loaded_potato_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Logo_350x250 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_350x250", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Logo_400x400 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_400x400", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property maximize_active_white_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximize_active_white_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property maximize_inactive_white_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximize_inactive_white_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Menu_920x250 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu_920x250", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property menu_white_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_white_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property minimize_thick_white_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_thick_white_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property minimize_thin_white_16x16 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_thin_white_16x16", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Order_920x250 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Order_920x250", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property order_white_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order_white_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property pepperoni_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pepperoni_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property pepperoni_pizza_small As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pepperoni_pizza_small", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        ''' </summary>
        Friend Shared ReadOnly Property pizza As Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("pizza", resourceCulture)
                Return CType(obj, Drawing.Icon)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property settings_white_thick_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_white_thick_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property settings_white_thin_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_white_thin_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Specials_920x250 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Specials_920x250", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property specialties_white_24x24 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("specialties_white_24x24", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property spinach_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spinach_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property supreme_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supreme_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property supreme_pizza_small As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supreme_pizza_small", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property taco_pizza As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taco_pizza", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Bacon_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Bacon_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_BananaPepper_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_BananaPepper_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_GreenBellPepper_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_GreenBellPepper_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Ham_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Ham_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_ItalianSausage_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_ItalianSausage_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Jalepeno_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Jalepeno_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Mushroom_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Mushroom_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Olives_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Olives_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Onion_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Onion_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pepperoni_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pepperoni_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Pineapple_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Pineapple_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_extra As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_extra", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_extra_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_extra_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_extra_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_extra_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_reg As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_reg", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_reg_L As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_reg_L", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property topping_Tomato_reg_R As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topping_Tomato_reg_R", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
